// idle-mmorpg-client/src/pages/Account/components/CharacterCard.tsx
import "./CharacterCard.css";
import React from "react";
import type { Character } from "../../../models";

interface CharacterCardProps {
    character: Character;
    onClick?: () => void;
}

export const CharacterCard: React.FC<CharacterCardProps> = ({ character, onClick }) => {
    const { name, attributes } = character;

    return (
        <div className="character-card" onClick={onClick}>
            <div className="character-header">
                <h3>{name}</h3>
            </div>
            {attributes ? (<div className="character-attributes">
                <p><strong>STR</strong>: {attributes.strength}</p>
                <p><strong>DEX</strong>: {attributes.dexterity}</p>
                <p><strong>CON</strong>: {attributes.constitution}</p>
                <p><strong>INT</strong>: {attributes.intelligence}</p>
                <p><strong>WIS</strong>: {attributes.wisdom}</p>
                <p><strong>CHA</strong>: {attributes.charisma}</p>
            </div>) : (<div className=".character-header">
                <p>No attributes.</p>
            </div>
            )}
        </div>
    );
};

// idle-mmorpg-client/src/app/pages/account/component/character-card/character-card.component.ts
import { Component, Input } from '@angular/core';
import { NgIf } from '@angular/common';

import { CardComponent } from '../../../../component';

import type { Character } from '../../../../model';

@Component({
    selector: 'app-character-card',
    templateUrl: './character-card.component.html',
    styleUrls: ['./character-card.component.scss'],
    imports: [
        NgIf,
        CardComponent,
    ]
})
export class CharacterCardComponent {
    @Input() character!: Character;
    @Input() onClick?: () => void;
}

<app-card [onClick]="onClick">
    <div class="character-header">
        <h3>{{ character.name }}</h3>
    </div>

    <div *ngIf="character.attributes; else noAttributes" class="character-attributes">
        <p><strong>STR</strong>: {{ character.attributes.strength }}</p>
        <p><strong>DEX</strong>: {{ character.attributes.dexterity }}</p>
        <p><strong>CON</strong>: {{ character.attributes.constitution }}</p>
        <p><strong>INT</strong>: {{ character.attributes.intelligence }}</p>
        <p><strong>WIS</strong>: {{ character.attributes.wisdom }}</p>
        <p><strong>CHA</strong>: {{ character.attributes.charisma }}</p>
    </div>

    <ng-template #noAttributes>
        <div class="character-header">
            <p>No attributes.</p>
        </div>
    </ng-template>
</app-card>
