// idle-mmorpg-client/src/components/atoms/StatusCircle/StatusCircle.tsx
import "./StatusCircle.css";

export type StatusType = "online" | "offline" | "error" | "loading" | "unknown";

interface StatusCircleProps {
    status: StatusType;
    size?: number;
}

export function StatusCircle({ status, size = 12 }: StatusCircleProps) {
    return (
        <span
            className={`status-circle ${status}`}
            style={{ width: size, height: size }}
            title={status}
        />
    );
}

// idle-mmorpg-client/src/app/pages/login/component/status-circle/status-circle.component.ts
import { Component, Input } from '@angular/core';
import { NgStyle } from '@angular/common';

export type StatusType = 'online' | 'offline' | 'error' | 'loading' | 'unknown';

@Component({
    selector: 'app-status-circle',
    templateUrl: './status-circle.component.html',
    styleUrls: ['./status-circle.component.scss'],
    imports: [
        NgStyle,
    ]
})

export class StatusCircleComponent {
    @Input() status: StatusType = 'unknown';
    @Input() size: number = 32;
}

<span class="status-circle {{ status }}" [ngStyle]="{ width: size + 'px', height: size + 'px' }"
    [attr.title]="status"></span>
