// idle-mmorpg-client/src/app/pages/login/component/login-form/login-form.component.ts
import { Component, inject } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormBuilder, ReactiveFormsModule, Validators } from "@angular/forms";
import { Router } from "@angular/router";

import { ButtonComponent } from "../../../../component";
import { InputFieldComponent } from "../../../../component";
import { PanelComponent } from "../../../../component";

import { AuthService } from "../../../../service/auth.service";
import { APIService } from "../../../../service/api.service";

@Component({
    selector: "app-login-form",
    templateUrl: "./login-form.component.html",
    styleUrls: ["./login-form.component.scss"],
    imports: [
        CommonModule,
        ReactiveFormsModule,
        PanelComponent,
        InputFieldComponent,
        ButtonComponent
    ],
})

export class LoginFormComponent {
    fb = inject(FormBuilder);
    authService = inject(AuthService);
    router = inject(Router);
    form = this.fb.group({
        username: ['', Validators.required],
        password: ['', Validators.required]
    });
    error: string | null = null;

    apiService = inject(APIService);

    async handleSubmit() {
        if (this.form.invalid) return;
        this.error = null;

        const { username, password } = this.form.value;

        try {
            const loginResponse = await this.apiService.postData<any>('/login', { username, password });

            if (!loginResponse?.sessionID || !loginResponse?.userID) {
                throw new Error('Invalid login response');
            }

            this.authService.login(loginResponse.userID, loginResponse.username, loginResponse.sessionID);
            this.router.navigate(['/account']);

        } catch (err: any) {
            console.error('Login failed:', err);
            this.error = err.message || 'Login failed.';
        }
    }
}

<form [formGroup]="form" (ngSubmit)="handleSubmit()">
    <app-panel>
        <h2>Login</h2>

        <app-input-field label="Username" type="text" formControlName="username" placeholder="Enter your username" />

        <app-input-field label="Password" type="password" formControlName="password"
            placeholder="Enter your password" />

        <app-button text="Login" type="submit" [disabled]="form.invalid" />

        @if(error){
        <p style="color: red;">Error: {{ error }}</p>
        }
    </app-panel>
</form>

// idle-mmorpg-client/src/pages/Login/components/LoginForm.tsx
import "./LoginForm.css";
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button, InputField, PanelVertical } from "../../../components";
import { useAuth } from "../../../context/AuthContext";
import { APIService } from "../../../service/APIService";

interface LoginResponse {
    userID: number;
    username: string;
    sessionID: string;
}

export function LoginForm() {
    const [username, setUsername] = useState("");
    const [password, setPassword] = useState("");
    const [error, setError] = useState<string | null>(null);
    const { login } = useAuth();
    const navigate = useNavigate();

    async function handleSubmit(e: React.FormEvent) {
        e.preventDefault();
        setError(null);

        try {
            const loginResponse = await APIService.postData<LoginResponse>('/login', { username, password });

            if (!loginResponse || !loginResponse.sessionID || !loginResponse.userID) {
                throw new Error("Invalid login response");
            }

            login(loginResponse.userID, loginResponse.username, loginResponse.sessionID);
            navigate("/account");
        } catch (err: any) {
            console.error("Login failed:", err);
            setError(err.message || "Login failed.");
        }
    }

    return (
        <form onSubmit={handleSubmit}>
            <PanelVertical>
                <h2>Login</h2>
                <InputField
                    label="Username"
                    type="text"
                    name="username"
                    value={username}
                    onChange={(e) => setUsername(e.target.value)}
                    placeholder="Enter your username"
                />
                <InputField
                    label="Password"
                    type="password"
                    name="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="Enter your password"
                />
                <Button text="Login" type="submit" />
                {error && <p style={{ color: "red" }}>{error}</p>}
            </PanelVertical>
        </form>
    );
}
