// idle-mmorpg-client/src/app/pages/login/component/server-form/server-form.component.ts
import { Component, inject, OnInit } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from "@angular/forms";

import { ButtonComponent } from "../../../../component";
import { InputFieldComponent } from "../../../../component";
import { PanelComponent } from "../../../../component";

import { StatusCircleComponent } from "../status-circle/status-circle.component";

import { APIService } from "../../../../service/api.service";
import { ServerService } from "../../../../service/server.service";


@Component({
    selector: "app-server-form",
    templateUrl: "./server-form.component.html",
    styleUrls: ["./server-form.component.scss"],
    imports: [
        CommonModule,
        ReactiveFormsModule,
        ButtonComponent,
        InputFieldComponent,
        PanelComponent,
        StatusCircleComponent,
    ]
})

export class ServerFormComponent implements OnInit {
    private fb = inject(FormBuilder);
    private apiService = inject(APIService);
    private serverService = inject(ServerService);

    form: FormGroup;
    status: 'online' | 'offline' | 'loading' | 'error' | 'unknown' = 'offline';
    error: string | null = null;

    constructor() {
        const server = this.serverService.getServer();
        this.form = this.fb.group({
            ip: [server?.address || '', Validators.required],
            port: [server?.port || '', Validators.required],
        });

        if (server) {
            this.status = 'loading';
        }
    }

    ngOnInit(): void {
        if (this.serverService.getServer()) {
            this.checkStatus();
        }
    }

    async checkStatus(): Promise<void> {
        try {
            await this.apiService.getStatus();
            this.status = 'online';
        } catch {
            this.status = 'error';
        }
    }

    async checkStatusWithParams(ip: string, port: string): Promise<boolean> {
        try {
            const cleanedIp = ip.replace(/^https?:\/\//, '');
            const response = await fetch(`http://${cleanedIp}:${port}/status`);
            if (!response.ok) throw new Error();
            this.status = 'online';
            return true;
        } catch {
            this.status = 'error';
            return false;
        }
    }

    async handleSubmit(): Promise<void> {
        this.error = null;
        this.status = 'loading';

        const { ip, port } = this.form.value;
        const ok = await this.checkStatusWithParams(ip, port);

        if (!ok) {
            this.error = 'Could not connect to the server.';
            return;
        }

        this.serverService.connect(ip, port);
    }
}

<form [formGroup]="form" (ngSubmit)="handleSubmit()">
    <app-panel>
        <div class="server-row">
            <app-status-circle [status]="status" />
            <h2>Server:</h2>

            <app-input-field label="IP Address" type="text" formControlName="ip" placeholder="127.0.0.1" />
            <app-input-field label="Port" type="text" formControlName="port" placeholder="8080" />

            <app-button text="Connect" type="submit" [disabled]="form.invalid || status === 'loading'" />

            @if(error){
            <p style="color: red;">Error: {{ error }}</p>
            }
        </div>
    </app-panel>
</form>

// idle-mmorpg-client/src/components/molecules/Form/ServerForm.tsx
import "./ServerForm.css";
import React, { useState, useEffect } from "react";
import { Button, InputField, PanelHorizontal, StatusCircle } from "../../atoms";
import { useServer } from "../../../contexts/ServerContext";
import { APIService } from "../../../services/APIService";

export function ServerForm() {
    const { connect, server } = useServer();
    const [ip, setIp] = useState(server?.address || "");
    const [port, setPort] = useState(server?.port || "");
    const [status, setStatus] = useState<"online" | "offline" | "loading" | "error" | "unknown">(
        server ? "loading" : "offline"
    );
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        if (server) checkStatus();
    }, [server]);

    async function checkStatusWithParams(ip: string, port: string): Promise<boolean> {
        try {
            const tempUrl = `http://${ip.replace(/^https?:\/\//, "")}:${port}`;
            const response = await fetch(`${tempUrl}/status`);
            if (!response.ok) throw new Error();
            setStatus("online");
            return true;
        } catch {
            setStatus("error");
            return false;
        }
    }

    async function checkStatus() {
        try {
            await APIService.getStatus();
            setStatus("online");
        } catch {
            setStatus("error");
        }
    }

    async function handleSubmit(e: React.FormEvent) {
        e.preventDefault();
        setError(null);
        setStatus("loading");

        const ok = await checkStatusWithParams(ip, port);
        if (!ok) {
            setError("Could not connect to the server.");
            return;
        }

        connect(ip, port);
    }

    return (
        <div className="server-form-wrapper">
            <form onSubmit={handleSubmit}>
                <PanelHorizontal>
                    <h2>Server:</h2>
                    <StatusCircle status={status} />
                    <InputField
                        label="IP Address"
                        name="ip"
                        value={ip}
                        onChange={(e) => setIp(e.target.value)}
                        placeholder="127.0.0.1"
                    />
                    <InputField
                        label="Port"
                        name="port"
                        value={port}
                        onChange={(e) => setPort(e.target.value)}
                        placeholder="8080"
                    />
                    <Button text={server ? "Reconnect" : "Connect"} type="submit" />
                    {error && <p style={{ color: "red" }}>{error}</p>}
                </PanelHorizontal>
            </form>
        </div>
    );
}
